server:
  port: 9004
  shutdown: graceful
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  application:
    name: results-svc
  cloud:
    stream:
      bindings:
        simulationCreate-in-0:
          destination: simulation-create
          group: ${spring.application.name}
  datasource:
    hikari:
      connection-timeout: 2000 #ms
      maximum-pool-size: 5
      # https://github.com/jhipster/generator-jhipster/issues/8146
      auto-commit: false
    password: password
    url: jdbc:postgresql://localhost:5432/portaldb
    username: user
  jpa:
    hibernate:
      ddl-auto: create-drop
  lifecycle:
    timeout-per-shutdown-phase: 15s
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
    connection-timeout: 5s
